### ISSUE TITLE
RtspClientSharp project as a reference vs forking?

### ISSUE THREAD

**Issue by kiranpradeep** [i-TechSoftware/RtspClientSharpCore#4]
This is not an issue: As a viewer, I like to understand the intention behind project better. Do we get any benefit by targetting netcore 3.0 on RtspClientSharp? Ofcourse, our example application could use netcore 3.0 apis, but that is irrelevant to RtspClientSharp project itself which could still have been in netstandard 2.0. 

This project contains full source of RtspClientSharp and use the project as a full copy. Isn't it better if it is used as a reference in csproj?

**Comment by askrinnik** [comment]
Since the author of the original repository doesn't develop the project, makes no sense to refer to it.
Moreover, you can't compile and run the application from the original repository. Aoutor of the fork included the compiled library ffmpeghelper.so in the project TestRtspClient
So, I vote for this repo :)
